---
- name: setup env
  hosts: all
  vars:
    docker_group_members:
      - vagrant
  roles:
    - role: angstwad.docker_ubuntu
      become: yes

  tasks:
    - name: Execute shell install script
      become: yes
      shell: curl -sL https://deb.nodesource.com/setup_6.x | bash -

    - name: install
      become: yes
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: true
      with_items:
        - git
        - nodejs

    - name: yarn install
      become: yes
      npm:
        global: yes
        name: yarn
      tags: npm
